<section>
	<form action="#" id="formAddRealisation" method="post" enctype="multipart/form-data">
		<input type="hidden" name="MAX_FILE_SIZE" value="10000000" />
		<label for="name">Nom :</label>
		<input type="text" name="name">
		<label for="urlImage">Image :</label>
		<input type="file" name="urlImage">
		<textarea name="description"></textarea>
		<label for="urlLink">URL :</label>
		<input type="text" name="urlLink">
		<button name="send">Envoyer</button>
	</form>
</section>