<section class="mainAdmin">
	<form action="#" id="formAddRealisation" method="post" enctype="multipart/form-data">
		<input type="hidden" name="MAX_FILE_SIZE" value="10000000" />
		<label for="name">Nom :</label>
		<input type="text" name="name">
		<label for="urlImage">Image :</label>
		<input type="file" name="urlImage">
		<textarea name="description"></textarea>
		<label for="href">href :</label>
		<input type="text" name="href">
		<button name="send">Envoyer</button>
	</form>
	<article>
		<?php require "message.php"; ?>
	</article>
</section>
