<section class="mainProject">
	<section>
		<svg viewBox="0 0 1740 150" preserveAspectRatio="xMinyMin meet">
			<path d="M 1740,0 L 1740,150 L 0,150 L 0,70 L 968,70 L 988,45"/>
	                        <text x="895" y="50">Projets</text>
	                        <a href="#" id="returnHome">
	                                <circle cx="1700" cy="40" r="20" transform="rotate(-90 1700 40)"/>
	                                <path d="M 1700,30 L 1700,50" transform="rotate(45 1700 40)"/>
	                                <path d="M 1690,40 L 1710,40" transform="rotate(45 1700 40)"/>
	                        </a>
				<a href="javascript:void(0)" id="persoRealisation">
	                        	<text x="100" y="115">En Cours</text>
					<path d="M 60,125 L 140,125 L 150,110"/>
				</a>
				<a href="javascript:void(0)" id="coRealisation">
					<text x="300" y="115">En Réflexion</text>
					<path class="hidden" d="M 240,125 L 355,125 L 365,110"/>
				</a>
		</svg>
	</section>
	<section>

	</section>
</section>
