<!DOCTYPE html>
<html>
        <head>
                <meta charset="utf-8">
                <link rel="stylesheet" href="ressources/style/css/font-awesome.min.css">
                <link rel="stylesheet" href="ressources/style/css/normalize.css">
                <link rel="stylesheet" href="ressources/style/css/style.css">
                <title>PortFolio De David-Naud</title>
                <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
                <script type="text/javascript" src="ressources/js/ajax.js"></script>
                <script type="text/javascript" src="ressources/js/event.js"></script>
                <script type="text/javascript" src="ressources/js/utilities.js"></script>
        </head>
        <body>
                <main id="main"></main>
                <script type="text/javascript" src="ressources/js/main.js"></script>
        </body>
</html>
