<!DOCTYPE html>
<html>
        <head>
                <meta charset="utf-8">
                <link rel="stylesheet" href="ressources/style/css/font-awesome.min.css">
                <link rel="stylesheet" href="ressources/style/css/normalize.css">
                <link rel="stylesheet" href="ressources/style/css/style.css">
                <title>PortFolio De David-Naud</title>
        </head>
        <body>
                <?php require_once "ressources/template/admin/admin.phtml" ?>
        </body>
</html>
