<!DOCTYPE html>
<html>
        <head>
                <meta charset="utf-8">
                <link rel="stylesheet" href="ressources/style/css/font-awesome.min.css">
                <link rel="stylesheet" href="ressources/style/css/normalize.css">
                <link rel="stylesheet" href="ressources/style/css/style.css">
                <title>PortFolio De David-Naud</title>
        </head>
        <body>
                <main id="main"></main>
                <?php include $main ?>
        </body>
</html>
